### ISSUE TITLE
Add French Language support

### ISSUE THREAD

**Issue by yunweneric** [yunweneric/flutter-widgethub#5]
### Context

The initial release of FWH is implemented in English. Inorder to make it accessible and inclusive, there is need for translation to other languages

#### Work to be done

- use [Easy localisation package](https://pub.dev/packages/easy_localization) to implement the locales for French Language
- Add a dropdown on the menu bar to change the language.

#### Ideal approach
- Following the bloc pattern, ensure you create a new bloc for langages and register it in the service locators
- You can provide it as a top level widget in the app.dart file
- Implement the logic to change the language in the bloc.
- Create a function in the utils folder to translate any text. Something like; UtilHelper.trans("text_to_be_translated")

**Comment by yunweneric** [comment]
Awesome ✅

**Comment by yunweneric** [comment]
This issue has. been resolved [With this PR](https://github.com/yunweneric/flutter-widgethub/pull/23)

**Comment by chendjou237** [comment]
Hello Yunweneric,

Thank you for your assistance in resolving the issue with the pull request.
I truly appreciate the professionalism and expertise you demonstrated.
Additionally, I wanted to share that, as a fellow developer, I have been
feeling a bit stagnant in my tech career over the past few weeks. I would
greatly value any advice or insights you might have on overcoming such a
phase and advancing further in this field.

Best regards,
Chendjou Honore

**Comment by yunweneric** [comment]
Awesome @chendjou237 

Contributing to open source is one of the greatest way to grow your tech career. I am glad you have ventured into that.
We will be running a mentorship program as from January 2025

Find more details here https://togeva.com
You can join the waitlist so we keep you posted!
