### ISSUE TITLE
The main page is very slow, heavy, lags, and causes glitches.

### ISSUE THREAD

**Issue by IldySilva** [yunweneric/flutter-widgethub#6]
I observed this behavior on the following browsers: Chrome, Edge, Brave, and Firefox.
but when i navigate to components route,it works fine

**Comment by yunweneric** [comment]
Hi @IldySilva 

Thank you for this feedback
Will you like to work on this?

**Comment by IldySilva** [comment]
Yy ,@yunweneric  I'll look at

**Comment by yunweneric** [comment]
This issue has been addressed by @IldySilva  in this MR
https://github.com/yunweneric/flutter-widgethub/pull/7
